FROM golang:1.26-alpine

RUN apk add --no-cache git curl build-base

RUN go install github.com/swaggo/swag/cmd/swag@v1.16.4 && \
    go install github.com/air-verse/air@latest && \
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5

WORKDIR /src/apps/identity-api

ENV CGO_ENABLED=0 \
    GOOS=linux

CMD ["air", "-c", ".air.toml"]
