services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_REGION: "${MINIO_REGION}"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - ./minio-data:/data

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/identity-api/internal/db/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  identity:
    build:
      context: .
      dockerfile: apps/identity-api/Dockerfile.dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/identity?sslmode=disable
      PORT: ${IDENTITY_API_PORT}
      GOCACHE: /root/.cache/go-build
      ALLOWED_ORIGINS: http://localhost:${WEB_PORTAL_PORT},http://127.0.0.1:${WEB_PORTAL_PORT}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
    ports:
      - "${IDENTITY_API_PORT}:${IDENTITY_API_PORT}"
    volumes:
      - ./apps/identity-api:/src/apps/identity-api
      - ./libs:/src/libs
      - identity_tmp:/src/apps/identity-api/tmp
      - identity_go_cache:/root/.cache/go-build
      - identity_go_mod:/go/pkg/mod
    extra_hosts:
      - "local.velotrace-identity-api:127.0.0.1"
    working_dir: /src/apps/identity-api
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:${IDENTITY_API_PORT}/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  bikes:
    build:
      context: .
      dockerfile: apps/bikes-api/Dockerfile.dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/identity?sslmode=disable
      PORT: ${BIKES_API_PORT}
      GOCACHE: /root/.cache/go-build
      ALLOWED_ORIGINS: http://localhost:${WEB_PORTAL_PORT},http://127.0.0.1:${WEB_PORTAL_PORT}
      JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
      STORAGE_ENDPOINT: "${STORAGE_ENDPOINT}"
      STORAGE_ACCESS_KEY: "${STORAGE_ACCESS_KEY}"
      STORAGE_SECRET_KEY: "${STORAGE_SECRET_KEY}"
      STORAGE_REGION: "${STORAGE_REGION}"
      STORAGE_BUCKET: "${STORAGE_BUCKET}"
      STORAGE_PUBLIC_BASE_URL: "${STORAGE_PUBLIC_BASE_URL}"
      STORAGE_PRESIGN_ENDPOINT: "${STORAGE_PRESIGN_ENDPOINT}"
    ports:
      - "${BIKES_API_PORT}:${BIKES_API_PORT}"
    volumes:
      - ./apps/bikes-api:/src/apps/bikes-api
      - ./libs:/src/libs
      - bikes_tmp:/src/apps/bikes-api/tmp
      - identity_go_cache:/root/.cache/go-build
      - identity_go_mod:/go/pkg/mod
    extra_hosts:
      - "local.velotrace-bikes-api:127.0.0.1"
    working_dir: /src/apps/bikes-api
    depends_on:
      db:
        condition: service_healthy
      identity:
        condition: service_healthy
      # minio:
      #   condition: service_healthy

  web-portal:
    build:
      context: ./apps/web-portal
      dockerfile: Dockerfile.dev
      args:
        PORT: ${WEB_PORTAL_PORT}
    ports:
      - "${WEB_PORTAL_PORT}:${WEB_PORTAL_PORT}"
    volumes:
      - ./apps/web-portal:/app
      - ./libs/api-contract:/app/libs/api-contract
      - ./tools:/app/tools
      - /app/node_modules
      - /app/libs/api-contract/identity-api/generated
      - /app/.nuxt
    environment:
      NODE_ENV: development
      NITRO_OUTPUT_DIR: .vercel/output
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      IDENTITY_API_URL: ${IDENTITY_API_URL}
    extra_hosts:
      - "local.velotrace-webportal:127.0.0.1"

volumes:
  postgres_data:
  identity_go_cache:
  identity_go_mod:
  identity_tmp:
  bikes_tmp:
  minio-data:
