FROM node:24-alpine

WORKDIR /app

ARG PORT
ARG ALLOWED_ORIGINS

COPY package*.json ./
RUN npm install

RUN npx nuxt prepare

COPY . .

RUN chmod +x scripts/sync-api.sh

EXPOSE ${PORT}

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=${PORT}

ENV WATCHPACK_POLLING=true

CMD ["sh", "-c", "npm run watch:contract & npm run dev"]
