FROM node:24-alpine

ARG PORT

RUN npm install -g corepack@latest && corepack enable && corepack prepare pnpm@10.33.0 --activate
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

WORKDIR /src

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/web-portal/package.json ./apps/web-portal/

RUN pnpm install --filter ./apps/web-portal... --frozen-lockfile

COPY apps/web-portal ./apps/web-portal/

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=${PORT}
ENV NODE_ENV=development

WORKDIR /src/apps/web-portal

RUN pnpm exec nx prepare web-portal

EXPOSE ${PORT}

CMD ["pnpm", "exec", "nx", "serve", "web-portal"]
