FROM node:24-alpine

WORKDIR /app

ARG PORT

RUN chown -R node:node /app

USER node

COPY --chown=node:node package*.json ./
RUN npm install

RUN npx nuxt prepare

COPY --chown=node:node . .

EXPOSE ${PORT}

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=${PORT}

ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "dev"]
