name: Deploy Identity API
on:
  push:
    branches: [main]
    paths:
      - "apps/identity-api/**"
      - "libs/shared/**"
      - ".github/workflows/api-deploy-template.yml"
      - ".github/workflows/deploy-identity.yml"

jobs:
  call-deploy:
    uses: ./.github/workflows/api-deploy-template.yml
    with:
      app-name: identity-api
      environment: dev
    secrets:
      RENDER_DEPLOY_HOOK: ${{ secrets.IDENTITY_API_RENDER_DEPLOY_HOOK }}
