name: Deploy Web Portal Production
on:
  push:
    branches: [dev]
    paths:
      - "apps/web-portal/**"
      - ".github/workflows/deploy-web-portal.yml"
      - ".github/workflows/web-portal-deploy-template.yml"
      - "libs/api-contract/**"
      - "package.json"
      - "vercel.json"
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/workflows/web-portal-deploy-template.yml
    with:
      vercel-env: Production
      is-prod: true
    secrets: inherit # Automatically passes all repo secrets