name: Deploy Bikes API
on:
  push:
    branches: [main]
    paths:
      - "apps/bikes-api/**"
      - "libs/shared/**"
      - ".github/workflows/api-deploy-template.yml"
      - ".github/workflows/deploy-bikes.yml"

jobs:
  call-deploy:
    uses: ./.github/workflows/api-deploy-template.yml
    with:
      app-name: bikes-api
      environment: dev
    secrets:
      RENDER_DEPLOY_HOOK: ${{ secrets.BIKES_API_RENDER_DEPLOY_HOOK }}
