name: Deploy Web Portal Preview to Vercel
on:
  push:
    branches-ignore: [main]
    paths:
      - "apps/web-portal/**"
      - ".github/workflows/deploy-web-portal-preview.yml"
      - "libs/api-contract/**"
      - "package.json"
      - "vercel.json"

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Check if Web Portal is Affected
        id: check_affected
        run: |
          # Run nx and store output. If nx fails, the script fails here (-e).
          AFFECTED_PROJECTS=$(npx -y nx show projects --affected --base=origin/main --head=HEAD)

          if echo "$AFFECTED_PROJECTS" | grep -q 'web-portal'; then
            echo "affected=true" >> $GITHUB_OUTPUT
          else
            echo "affected=false" >> $GITHUB_OUTPUT
          fi

      - name: Prepare API Contracts
        # if: steps.check_affected.outputs.affected == 'true'
        run: |
          cp -r libs apps/web-portal/
          npx nx run web-portal:generate:contracts

      - name: Run Tests
        # if: steps.check_affected.outputs.affected == 'true'
        run: npx nx run web-portal:test

      - name: Build Web Portal (Preview)
        # if: steps.check_affected.outputs.affected == 'true'
        run: npx nx run web-portal:build --verbose

      - name: Deploy Preview to Vercel
        # if: steps.check_affected.outputs.affected == 'true'
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          NITRO_OUTPUT_DIR: ${{ secrets.NITRO_OUTPUT_DIR }}
          IDENTITY_API_URL: ${{ secrets.IDENTITY_API_URL }}
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --meta githubCommitRef=${{ github.ref_name }} \
          --meta githubCommitSha=${{ github.sha }} \
          --meta githubCommitAuthorName="${{ github.actor }}"
